[package]
name = "spotlight"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "spotlight"
path = "src/main.rs"

[dependencies]
spotlight-core.workspace = true
spotlight-ui.workspace = true
ext-apps.workspace = true
ext-calculator.workspace = true
ext-clipboard.workspace = true
ext-gmail.workspace = true
ext-jira.workspace = true
ext-music.workspace = true
ext-scripts.workspace = true
