[package]
name = "ext-gmail"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
anyhow.workspace = true
ureq.workspace = true
serde.workspace = true
serde_json.workspace = true
imap.workspace = true
native-tls.workspace = true
mail-parser.workspace = true
image.workspace = true
spotlight-htmlview.workspace = true
spotlight-config.workspace = true
spotlight-ui.workspace = true
