[package]
name = "ext-gmail"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
imap.workspace = true
native-tls.workspace = true
mail-parser.workspace = true
anyrender.workspace = true
anyrender_vello_cpu.workspace = true
blitz-dom.workspace = true
blitz-html.workspace = true
blitz-paint.workspace = true
blitz-traits.workspace = true
image.workspace = true
log.workspace = true
spotlight-config.workspace = true
spotlight-ui.workspace = true
